<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net48</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>TradingChartPanel.DataAdapters</AssemblyName>
    <RootNamespace>TradingChartPanel.DataAdapters</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TradingChartPanel.Core/TradingChartPanel.Core.csproj" />
  </ItemGroup>
</Project>
