<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net6.0-windows;net48</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>TradingChartPanel.WPF</AssemblyName>
    <RootNamespace>TradingChartPanel.WPF</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TradingChartPanel.Core/TradingChartPanel.Core.csproj" />
  </ItemGroup>
</Project>
